### ISSUE TITLE
Admin panel URL requires trailing slash

### ISSUE THREAD

**Issue by Nathan-LloydBore** [MerginMaps/server#112]
I have a Mergin CE 22.03 instance running on Ubuntu. I can access the dashboard just fine but when trying to navigate to /admin it just times out. My account was created with the --is-admin tag when I launched the server.

**Comment by holgerbermeo** [comment]
So http://localhost:5000/admin/ not like that http://localhost:5000/admin

**Comment by tomasMizera** [comment]
Hi guys, thanks for reporting this bug

**Comment by tomasMizera** [comment]
Expected behavior: `<server_url>/admin` and `<server_url>/admin/` will both navigate to the admin panel

**Comment by uprel** [comment]
After setting up CE, I can access admin panel with this URL: `http://my_server:8080/admin/`. When I try without last backslash it redirects to port 80  -  `http://my_server/admin/` and by default config admin panel does not work in that case.
