### ISSUE TITLE
error in mergin server when changing external ip

### ISSUE THREAD

**Issue by holgerbermeo** [MerginMaps/server#123]
I'm doing some tests on a virtual machine in Google Cloud. At first everything worked well. But for some reasons the machine had to be restarted and the external IP changed. I raised the mergin server again, but when I wanted to synchronize new data in both Qgis and the mobile application, I got an error that I show in the images. Note: I did change the server IP in both the Qgis plugin and the mobile application.

![WhatsApp Image 2023-10-16 at 10 32 47 AM](https://github.com/MerginMaps/mergin/assets/59984753/87cef071-bb60-42e9-b60a-2a18b528f6ef)
![WhatsApp Image 2023-10-16 at 10 32 35 AM](https://github.com/MerginMaps/mergin/assets/59984753/5112ce68-ab96-4403-b0e8-f211590bc7d6)

**Comment by tomasMizera** [comment]
Hello @holgerbermeo, you can join our community slack channel, you might get answer there: https://merginmaps.com/community/join
