### ISSUE TITLE
I can't create my first project

### ISSUE THREAD

**Issue by sgalvi** [MerginMaps/server#167]
Hello,

I'm having trouble creating my first project on Mergin. I've tried creating it from the web menu and also from QGIS, but I'm not able to do so. I've attached screenshots and the .prod.env file for your reference.

Can you please help me with this issue?

Thank you|
![Screenshot from 2024-01-22 11-42-30](https://github.com/MerginMaps/server/assets/153731136/4a537d5b-ba49-4f1f-8862-b78c18688d08)
![Screenshot from 2024-01-22 11-42-08](https://github.com/MerginMaps/server/assets/153731136/07dcfa87-f73f-467f-8dae-25df3d391fa8)
[prod.env.txt](https://github.com/MerginMaps/server/files/14009008/prod.env.txt)

the .prod.env
https://pastebin.com/3WpJPvkQ
password: github[](url)

**Comment by MarcelGeo** [comment]
Hi @sgalvi could you try it again and provide logs from mergin backend?

**Comment by sgalvi** [comment]
I tried both ways. The result is always the same. 
I'll leave attached what it generates when I launch the dockers. Can you tell me where the logs are saved? I can't find anything.
[mergin_results.txt](https://github.com/MerginMaps/server/files/14021214/mergin_results.txt)

Another problem I'm facing is the following: when I create a user and set them as an administrator, I only see the home, project, and user profile tabs.

Additionally, I have a question about email verification. Since I haven't configured a mail server, I don't receive the confirmation email. Is it necessary to set up a mail server? Could it work using smtp.gmail.com? Thank you for your patience

**Comment by MarcelGeo** [comment]
I think you can rewrite GLOBAL_WORKSPACE to mergin and start again. I don't see any logs from creating project in attached file.
