### ISSUE TITLE
Map section in my mergin project

### ISSUE THREAD

**Issue by sgalvi** [MerginMaps/server#172]
I saw that some of you have a "map preview" of the project from the browser. How could I integrate this function into my project too? Thank's!
![Screenshot from 2024-02-05 12-15-05](https://github.com/MerginMaps/server/assets/153731136/4abfda44-3961-4136-b05a-fa4d472e63c1)

**Comment by tomasMizera** [comment]
Hi @sgalvi, this is a feature of paid plans on our cloud version. Feel free to explore our pricing https://merginmaps.com/pricing
