### ISSUE TITLE
App not finding custom server

### ISSUE THREAD

**Issue by luc-girod** [MerginMaps/server#189]
Hello!

I have installed merginmaps on a server for my university, and I am struggling with getting the app to work. I have setup the docker to open on port 8081 (8080 isn't openable to the outside of the organization), and connecting to it through a browser and the QGIS plugin is no issues. Through the app though, it just doesn't work. I have input the correct url in the little "custom URL" space as "http://MYURL:8081".

Is the app expecting another port?

**Comment by saberraz** [comment]
hi @luc-girod , could you make sure:
1- use HTTPS instead of HTTP
2- You place / at the end of the url, i.e. https://MYURL:8081/
3- Press :heavy_check_mark: when you edit the custom server location on mobile
