### ISSUE TITLE
Wrong .prod.env values for LOCAL_PROJECTS and TEMP_DIR

### ISSUE THREAD

**Issue by uprel** [MerginMaps/server#202]
This lines in .prod.env cannot be like this:

https://github.com/MerginMaps/server/blob/a0cf751bdc0537a859edb83653004dc158ec5c29/.prod.env#L12

https://github.com/MerginMaps/server/blob/a0cf751bdc0537a859edb83653004dc158ec5c29/.prod.env#L27

Using this configuration I ended up with such folder names in docker:
![image](https://github.com/MerginMaps/server/assets/7328417/b371c0bd-804c-4eee-a16f-14d36c12dbc0)

This is surelly wrong, so I commented lines out to use default values.

**Comment by uprel** [comment]
Actually LOCAL_PROJECTS should be this to match value in docker-compose.yml
`LOCAL_PROJECTS=/data`

and then matching TEMP_DIR could go to commented value:
`TEMP_DIR=/data/tmp`

**Comment by MarcelGeo** [comment]
@jozef-budac follow instructions in PR and try it again. Just quick test :)

**Comment by jozef-budac** [comment]
It looks fixed in the new version.
