### ISSUE TITLE
/admin/projects image load from external dashboard creator

### ISSUE THREAD

**Issue by MarcHagen** [MerginMaps/server#246]
Does it seem strange that we require this?

https://github.com/MerginMaps/server/blob/17fd7b84bb092e4fb099fae6bd863f5559f2244a/web-app/packages/lib-vue2/src/modules/layout/store.ts#L17

```
GET https://demos.creative-tim.com/material-dashboard/assets/img/sidebar-1.jpg net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin 403 (Forbidden)
```

**Comment by MarcelGeo** [comment]
Hello @MarcHagen ... We are planning to completely remove lib-vue2 in this year. Dashboard is using new design and this design will be applied to the admin.
