### ISSUE TITLE
Error 403 when synchronizing between Androïd device and custom Mergin Server

### ISSUE THREAD

**Issue by AlexGacon** [MerginMaps/server#250]
Hi there,

We are trying to implement Mergin Maps on Azure Kubernetes Engines and I have the following issue when testing with my Android device: when I want to sync a project FROM the device to the server, the sync stopped after few seconds and displays a 403 message from Azure Gateway.

I manage to see the list of the projects from the device and to download them. I even manage to create an empty project on the device and to upload it on the server. But as soon as I start adding data to the project on the device, I have the error.

**Comment by MarcelGeo** [comment]
Hello @AlexGacon ... I'm not sure If this issue is related to azure or mergin maps... do you have any reasonable logs from pod where server is deployed?

**Comment by AlexGacon** [comment]
@MarcelGeo hello

Here is the log I got from the server pod before the 403 Azure message on Mergin Apps

[ACCESS] 10.176.240.20, 192.168.0.94 GET /v1/project/mergin/Monprojet since=v2 HTTP/1.0 200 1390 - "Input/2024.3.0 (android/10.0)" 13668 <63>
[INFO] [63] Upload transaction 2282137d-8979-43cb-be35-f6126ff039bb created for project: 8167f7f2-fbdc-4ae3-89c2-26c7db803f20, version: v1
[ACCESS] 10.176.240.20, 192.168.0.94 POST /v1/project/push/mergin/Monprojet  HTTP/1.0 200 60 - "Input/2024.3.0 (android/10.0)" 151778 <63>

I don't see any calls to the API after that.

**Comment by MarcelGeo** [comment]
> @MarcelGeo hello
> 
> Here is the log I got from the server pod before the 403 Azure message on Mergin Apps
> 
> [ACCESS] 10.176.240.20, 192.168.0.94 GET /v1/project/mergin/Monprojet since=v2 HTTP/1.0 200 1390 - "Input/2024.3.0 (android/10.0)" 13668 <63> [INFO] [63] Upload transaction 2282137d-8979-43cb-be35-f6126ff039bb created for project: 8167f7f2-fbdc-4ae3-89c2-26c7db803f20, version: v1 [ACCESS] 10.176.240.20, 192.168.0.94 POST /v1/project/push/mergin/Monprojet HTTP/1.0 200 60 - "Input/2024.3.0 (android/10.0)" 151778 <63>
> 
> I don't see any calls to the API after that.

Mhh... I don't see any 403 from our server there.

**Comment by AlexGacon** [comment]
Hello @MarcelGeo.

I will close the ticket: the issue was indeed on the Azure API Gateway which had a size limit configured too low for merginmaps usage. Removing this limit solved the issue.

Thanks for your help.
