### ISSUE TITLE
Cannot download files from project

### ISSUE THREAD

**Issue by owenh28** [MerginMaps/server#257]
I just setup an instance, I am forwarding through Nginx Proxy Manager with https enabled but not forced. When I try to download an individual file from the project, I get a 'Site Can't Be Reached' 404 Error. This does not happen when I download the entire project as a zip file. I have tried with and without X_ACCEL enabled. The server log shows: 
```[ACCESS] 10.6.0.3, 172.22.0.1 GET /v1/project/raw/mergin/ALT_Mobile file=Trails.gpkg&random=0.08892672966096038 HTTP/1.0 200 0 https://mergin.mydomain.tld/projects/mergin/ALT_Mobile/tree?file_path=Trails.gpkg "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 8036 <15>```

**Comment by MarcelGeo** [comment]
Hello @owenh28 I see 200 http status code.

[ACCESS] 10.6.0.3, 172.22.0.1 GET /v1/project/raw/mergin/ALT_Mobile file=Trails.gpkg&random=0.08892672966096038 HTTP/1.0 **200** 0 https://mergin.mydomain.tld/projects/mergin/ALT_Mobile/tree?file_path=Trails.gpkg "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 8036 <15>

**Comment by gromain** [comment]
Hello,

I believe I meet the same issue.
I've deployed a self hosted server, version 2024.2.2, following the instructions provided.
I've used the docker-compose file from the tagged version 2024.2.2 (not from master). The instructions don't specify which docker-compose version to use, so this could be an area of improvement.

After uploading a simple project from QGIS, I cannot download any files, either from the app or the web interface.

Here is a log example, from the `merginmaps-proxy` container of such an issue:
```
2024-09-26T12:42:35.625361120Z 192.168.1.231 - - [26/Sep/2024:12:42:35 +0000] "GET /v1/project/raw/tests/test_project?file=separation.gpkg&random=0.1455624417134156 HTTP/1.1" 404 153 "https://hostname.tld/projects/tests/test_project/tree?file_path=separation.gpkg" "Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0" "192.168.1.1"
2024-09-26T12:42:35.625348041Z 2024/09/26 12:42:35 [error] 36#36: *137 open() "/data49/2d51b7bec7f4e5e1be9006919418aaf9/v1/separation.gpkg" failed (2: No such file or directory), client: 192.168.1.231, server: _, request: "GET /v1/project/raw/tests/test_project?file=separation.gpkg&random=0.1455624417134156 HTTP/1.1", upstream: "http://172.19.0.5:5000/v1/project/raw/tests/test_project?file=separation.gpkg&random=0.1455624417134156", host: "hostname.tld", referrer: "https://hostname.tld/projects/tests/test_project/tree?file_path=separation.gpkg"
```


It looks like `merginmaps-server` is trying to retrieve the file from `/data49/2d51b7bec7f4e5e1be9006919418aaf9/v1/separation.gpkg`. Did you notice the missing `/` after `/data` ?

Regarding this container, I only have this on the logs:
```
2024-09-26T12:42:35.625301057Z [ACCESS] 192.168.1.1, 192.168.1.231 GET /v1/project/raw/tests/test_project file=separation.gpkg&random=0.1455624417134156 HTTP/1.0 200 0 https://hostname.tld/projects/tests/test_project/tree?file_path=separation.gpkg "Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0" 17308 <14>
```

I've tried to update `.prod.env` `LOCAL_PROJECTS` key to `/data/` to include the missing slash at the end, but it didn't change the outcome.

Anything more I can do on my side to help solve this issue?

**Comment by owenh28** [comment]
I think it was a permission error with the data folder and the proxy container. I added `group_add` to my docker-compose file under the proxy container. Here is the section:

```proxy:
        image: nginx
        container_name: merginmaps-proxy
        restart: always
        group_add: 
            - 999
        ports:
            - "8081:80"
        volumes:
            - ./projects:/data # map data dir to host
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - merginmaps
```
Additionally, you can try to chmod the projects folder with 777 or 755 to test. There may have been one more thing I did to fix the issue, I will let you know if I remember anything else.

**Comment by gromain** [comment]
Thanks a lot.

I've tried all of your suggestions, but they didn't help however. And it still looks like the path requested isn't right.

**Comment by gromain** [comment]
I think I found a part of the origin of the issue (at least for me).

A missing slash in nginx.conf was all it took, here:
https://github.com/MerginMaps/server/blob/50cb8da122b5124b19a9e12119d10682eb157e73/nginx.conf#L52

But now, I get a 403 forbidden error.

The proxy logs an access denied request:
```
2024/09/26 14:21:03 [error] 29#29: *29 open() "/data/49/2d51b7bec7f4e5e1be9006919418aaf9/v1/appuis.gpkg" failed (13: Permission denied), client: 192.168.1.231, server: _, request: "GET /v1/project/raw/tests/test_project?file=appuis.gpkg&random=0.9069902692853269 HTTP/1.1", upstream: "http://172.22.0.5:5000/v1/project/raw/tests/test_project?file=appuis.gpkg&random=0.9069902692853269", host: "hostname.tld", referrer: "https://hostname.tld/projects/tests/test_project/tree?file_path=appuis.gpkg"
2024/09/26 14:24:06 [error] 34#34: *71 open() "/data/b8/a5599968f4dd6fd9e44571abe44d3172/v1/tracking_layer.gpkg" failed (13: Permission denied), client: 192.168.1.231, server: _, request: "GET /v1/project/raw/tests/test_project?file=tracking_layer.gpkg&random=0.02775607058972107 HTTP/1.1", upstream: "http://172.22.0.5:5000/v1/project/raw/tests/test_project?file=tracking_layer.gpkg&random=0.02775607058972107", host: "hostname.tld", referrer: "https://hostname.tld/projects/tests/test_project/tree?file_path=tracking_layer.gpkg"
```

The folder `projects` has been properly setup with `chmod` and `chown` as detailed in the documentation.

**Comment by owenh28** [comment]
Can you enter the data folder and run a `ls -al` command? It looks like a permission issue now.

**Comment by MarcelGeo** [comment]
Hello @gromain / @owenh28 can you guys share your configuration of server? It's usefull to see also your permissions hee.

**Comment by gromain** [comment]
@MarcelGeo, I feel like it's a permission issue indeed.

I've tried to `chmod 755 -R projects` and it solved the access problem. However, as soon as I update/upload a new element, the changes are reverted (at least for the modified file) and download don't work anymore.

I've set up Mergin server on Alpine Linux 3.20.3, and followed the instructions at https://merginmaps.com/docs/server/install/ using the docker-compose file from the 2024.2.2 release (which is different from the one in master.

Here are the permissions of the project folder (I redid a new server for this to remove any possibility of interference from my previous tests):
```
mergin:~/server# ls -anl projects/**/**
projects/51/43d9b7ea209baf3ab5c8dfc6e1b3ebd6:
total 12
drwxr-s---    3 901      999           4096 Sep 27 08:49 .
drwxr-s---    3 901      999           4096 Sep 27 08:49 ..
drwxr-s---    2 901      999           4096 Sep 27 08:49 v1

projects/tmp/f2213132-2b7e-4a49-9353-e7ca4c9cf531:
total 12
drwxr-s---    3 901      999           4096 Sep 27 08:49 .
drwxr-s---    3 901      999           4096 Sep 27 08:49 ..
drwxr-s---    3 901      999           4096 Sep 27 08:49 51
mergin:~/server# ls -anl projects/**/**/**
projects/51/43d9b7ea209baf3ab5c8dfc6e1b3ebd6/v1:
total 220
drwxr-s---    2 901      999           4096 Sep 27 08:49 .
drwxr-s---    3 901      999           4096 Sep 27 08:49 ..
-rw-r-----    1 901      999          98304 Sep 27 08:49 data.gpkg
-rw-r-----    1 901      999          18782 Sep 27 08:49 test_project.qgz
-rw-r-----    1 901      999          98304 Sep 27 08:49 tracking_layer.gpkg

projects/tmp/f2213132-2b7e-4a49-9353-e7ca4c9cf531/51:
total 12
drwxr-s---    3 901      999           4096 Sep 27 08:49 .
drwxr-s---    3 901      999           4096 Sep 27 08:49 ..
drwxr-s---    3 901      999           4096 Sep 27 08:49 43d9b7ea209baf3ab5c8dfc6e1b3ebd6
```

The project files don't appear to have the s flag set for the group, which would explain why nginx can't access them (even when I add the group_add 999 directive in the compose file).

**Comment by owenh28** [comment]
Here is my folder structure (the input group has the 999 id):
```
~/mergin
-rw-r--r--.  1      my_user             my_user     1.2K Sep  1 03:00 docker-compose.yml
drwx------. 19      systemd-coredump    root        4.0K Sep  1 12:16 mergin_db
-rw-r--r--.  1      my_user             my_user     1.8K Sep  1 12:16 nginx.conf
drwxr-sr-x.  4      901                 input       27   Aug 24 21:00 projects

~/mergin/projects
drwxr-s---.  3      901                 input       46   Aug 17 02:54 7a
drwxr-s---.  2      901                 input       6    Sep  1 21:00 tmp

~/mergin/projects/7a
drwxr-s---.  6      901                 input       46   Aug 18 23:45 fea64f8f4ccf63a42943d17ba8532226

~/mergin/projects/7a/fea64f8f4ccf63a42943d17ba8532226
drwxr-s---.  2      901                 input       46   Aug 17 02:54 v1
drwxr-s---.  2      901                 input       27   Aug 18 21:23 v2
drwxr-s---.  2      901                 input       71   Aug 18 21:28 v3
drwxr-s---.  2      901                 input       27   Aug 18 23:45 v4

~/mergin/projects/7a/fea64f8f4ccf63a42943d17ba8532226/v3
-rw-r-----.  1      901                 input       70K  Aug 18 21:28 ALT_Field.qgz
-rw-r-----.  1      901                 input       69   Aug 18 21:28 mergin-config.json
-rw-r-----.  1      901                 input       96K  Aug 18 21:28 Notes.gpkg
```

**Comment by MarcelGeo** [comment]
From your description, I have following suggestions to test:

- Are there any selinux rules appended to /projects on your machine? It's always funny to play with that. 
- you can try to add ```:z``` to volume mount for nginx 

```
volumes:
            - ./projects:/data:z # map data dir to host
```
- you can try to run docker compose with sudo

**Comment by gromain** [comment]
There are no selinux rules (selinux is not even a part of a base alpine installation).

The `:z` addition did not help either.

Finally, docker compose is already running as root.

I'll try to set up mergin again on a debian VM to see if it changes anything and will document the changes. I'll create the PR for the documentation to include a recommended distribution to avoid this kind of question in the future. 

By the way, on this, would you prefer ubuntu server or debian?

**Comment by MarcelGeo** [comment]
I think, there should be issues with installation of docker and permissions on alpine. Let me know If everything is running @gromain .

**Comment by gromain** [comment]
Ok, this is super weird.

Vanilly debian bookworm, brand new. Setup the repository using the following:
```
git clone --depth=1 --branch 2024.2.2 https://github.com/MerginMaps/server.git
cd server
mkdir projects
sudo chown -R  901:999 ./projects/
sudo chmod g+s ./projects/
docker-compose -f docker-compose.yml up -d
docker exec merginmaps-server flask init-db
docker exec merginmaps-server flask user create myuser mypass --is-admin --email myemail
```

Created a new project inside the Mergin Maps app, added a point to the survey.
Synchronized with the server without issue.

Now when I tried to retrieve the data from the webserver, same 404 issue as before. I had to modify the `/download/` location in `nginx.conf` to the following:
```
   location /download/ {
     internal;
     alias   /data/; # Please note the added slash after data 
   }
```

But then once again, 403 error.

This sounds like an error with nginx.

Should I get the `docker-compose` file from master?

**Comment by MarcelGeo** [comment]
Ah ha, @gromain ... do you have enabled ```USE_X_ACCEL``` variable? If yes try to disable It in .prod.env... remove container, start new docker-compose.

**Comment by gromain** [comment]
@MarcelGeo that was it! 

I forgot to mention my `.prod.env` configuration. What it is with this that causes the issue? I initially used this because I saw that merginserver is configured with nginx inside, so felt like I had to activate this.

**Comment by owenh28** [comment]
I am at work right now, but I will send my testing steps when I get home
