### ISSUE TITLE
Data writers role

### ISSUE THREAD

**Issue by dracic** [MerginMaps/server#30]
I think it would be useful if we had "data writer" role for users who will only be able to change data and sync those changes to Mergin, and not be able to push changes in data structure (new layers, existing layers) or qgz changes. In small teams this is not an issue, but in big teams, when some of them have some knowledge of QGIS, some changes can be pushed accidentally or intentionally but unaware of potential conflicts and problems. We cannot control who is using only Input, and who is using Input and Qgis. Perhaps in future "data writers" could make some "pull request" for new layers or qgz changes to "project writers" and "owners". I think the best solution is to enable "owners" to make all changes, and "writers" just data changes.

**Comment by PeterPetrik** [comment]
This is a feature requested from more clients and it is on our agenda. Unfortunately, we are baking new Mergin CE/EE release, so we can focus on this feature later in the year.

**Comment by PeterPetrik** [comment]
If you are interested in the feature, drop me mail at peter.petrik@lutraconsulting.co.uk, we started to gather requirements :)
