### ISSUE TITLE
Project access request doesn't show in the project settings

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/server#36]
Project access request is displayed only on the dashboard, it doesn't show in the Access requests in the project's settings.
![access_issue_dashboard](https://user-images.githubusercontent.com/94905350/176223948-1f5d5a7e-6585-44ec-b0c8-5d36d61a5e1c.png)
![access_issue_settings](https://user-images.githubusercontent.com/94905350/176223954-402be95e-f108-46af-88fd-efab15d9d6e6.png)

**Comment by varmar05** [comment]
Fixed in 2023.2.0
