### ISSUE TITLE
Mergin CE with Docker on Ubuntu 18.04 steps after installation

### ISSUE THREAD

**Issue by geomoes** [MerginMaps/server#41]
Hi, 
I'm new to Docker and
I followed the instructions to install mergin via Docker on our server (Ubuntu 18.04 on e.g. 'our_server.com').
Now I have 
- mergin-server
- mergin-db
- mergin-redis
running,
but I have no idea what are the next steps.

How can I access the mergin-server and the admin panel or how can I
connect to QGIS trough the Mergin Maps Plugin to create and manage new projects?

**Comment by jusabatier** [comment]
You can access the webapp via : http://localhost:5000

Maybe your enterprise firewall block port 5000, so you can map `mergin-server` to port 80 : 

> ports:
>       - 80:5000

This work for me.

**Comment by varmar05** [comment]
Hi @geomoes, 
you can find guides to set up and manage your server:
- running own server https://merginmaps.com/docs/dev/mergince/#how-to-deploy-mergin-maps-ce.
- managing server from clients https://merginmaps.com/docs/manage/plugin-multi-server-use/#custom-server-configuration.

**Comment by rmarzocchi84** [comment]
I have a similar problem. 

I run 

```
sudo docker-compose -f docker-compose.yml up
```

Probably I not correctly serup the network (`networks: `section)?

I do not change the docker.compose.yml file
```
version: "3.7"
networks:
  merginmaps:

services:
  db:
    image: postgres:14
```

**Comment by tomasMizera** [comment]
This task has been stale for a while now, closing. Feel free to reopen it if needed!

**Comment by wojtek19022** [comment]
@tomasMizera I encountered similar issue as @rmarzocchi84. This happened after upgrade of Mergin Maps server from 2.0 to 6.1. Got the same notification as on second picture from @rmarzocchi84

**Comment by wojtek19022** [comment]
Thank you for check up @tomasMizera ! Glad to hear that! Can't wait for a fix
