### ISSUE TITLE
Don't receive email in my account email 

### ISSUE THREAD

**Issue by tuankhanh78** [MerginMaps/server#44]
When I click on the button "Send Confirmation Email" from the Dashboard, the notification appears and it's written "Email was sent to address : ... " but I don't receive the email. 
I have the same issue in my Profile view when I click on the button "Verify Email" : 
1. the modal is displayed
2. I click on "Send" button but I don't receive any email.
Do you have an idea about this issue ?
Thanks

**Comment by varmar05** [comment]
Hi @tuankhanh78, it seems like configuration issue. I suggest to start with new server version (2023.2.0) and follow guide https://merginmaps.com/docs/dev/mergince/#how-to-deploy-mergin-maps-ce
Then double check SMTP works correctly (e.g. using the same settings outside of Mergin Maps).

**Comment by tuankhanh78** [comment]
Hi varmar05,

It is working fine now with the new release 2023.2.0
Thank a lot
