### ISSUE TITLE
User creation via admin page

### ISSUE THREAD

**Issue by jusabatier** [MerginMaps/server#46]
I can't found a way to create a new user in the webapp.

When I get to "/admin", I can manage existing users account, but can't create a new one.

Is the bash docker command the only way to do it ?

**Comment by saberraz** [comment]
You can add it through docker:
`add-user USERNAME topsecret --email admin@example.com`

**Comment by jusabatier** [comment]
I know that, but is it the only way to create a user ?

I have some teammates who don't have access to the server's console, but only to the webapp.
So I suggest to add the ability to create an account via the admin page if it's not possible.

**Comment by varmar05** [comment]
It is available in version 2023.2.0
![image](https://user-images.githubusercontent.com/23185498/229513433-b5947d6d-6180-42dd-9171-c42e98551271.png)
