### ISSUE TITLE
Docker compose's PWD problem when using systemd

### ISSUE THREAD

**Issue by jusabatier** [MerginMaps/server#56]
I tried to set up a systemd file to launch mergin at startup : 

```
[Unit]
Description=Docker Compose Application Service
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/home/user/mergin
ExecStart=/usr/local/bin/docker-compose up -d
ExecStop=/usr/local/bin/docker-compose down
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
```

But when I try to launch the service, it complain about the nginx.conf file mount.
It try to mount it from the root, becouse of the `${PWD}`used here : https://github.com/MerginMaps/mergin/blob/master/docker-compose.yml#L55

A solution is to replace it with the full path to the nginx.conf file.

I share it, maybe it could be useful to others.

**Comment by alhirzel** [comment]
I am encountering this as well when trying to launch the Mergin Maps server via docker compose using ansible. I have created #132 .

**Comment by tomasMizera** [comment]
Thanks guys for reporting and fixing this issue. @alhirzel we will merge your change once you sign the licence here: https://github.com/MerginMaps/server/blob/master/LICENSES/CLA-signed-list.md
